config/routes.rb
Rails.application.routes.draw do
  
  
 resources :posts
  # root 'demo#index'
  # get 'article/index'
  # get 'article/:id',to: 'article#show',as: 'article'
  # get 'artcile/'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :author, presence: :true
end

app/models/post.rb
class Post < ApplicationRecord
  include ::PostsHelper
  validates :author,  presence: :true

  def tester
    p "*"*100
    p helper3
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/help.rb
module Help
  def test
    p "I am from Include Module"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Help
  include PostsHelper
  require 'require'

  def index
    @post=Post.all
  end

  def show
    @post= Post.find(params[:id])
    @s_id=session[:session_id]  
    session[:session_id]="My Session"
    PostsController.new.test
    t=CheckRequire.new.test
    # helper
    byebug
  end

  def destroy
    @post=Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def edit
    @post=Post.find(params[:id])
  end

  def update
    @post=Post.find(
    params[:id]
    )
    if @post.update(check_params)
      redirect_to posts_path
    else render 'edit'
    end
  end

  def new
    @post= Post.new
  end

  def create
    # byebug
    @post= Post.new(check_params)
    if @post.save
      redirect_to posts_path
    else 
      render 'new'
  end
end
private
def check_params
  params.require(:post).permit(:author, :ptype)
end

end

app/controllers/require.rb
class CheckRequire
  def test
    p "This Test from Require"
  end 
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/posts_helper.rb
module PostsHelper
def helper1
  p 'I am a helper from Model1'
end

def helper2
  p 'I am a helper from Model2'
end

def helper3
  1 == 2
  
end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for @post do |p| %>
<%= p.label :Author%>
<%= p.text_field :author%>
<%= p.label :ptype, "Post Type"%>
<%= p.text_field :ptype %>
   <%= p.submit "Update Post"%>
  
<% end %>
  

app/views/posts/index.html.erb
<h1>All Posts</h1>

<% @post.each do |p|%>
  <p>
  <ul>
<li>
  <p><%= link_to p.author, post_path(p.id) %><p>
  <p>Post Type: <%= p.ptype%></p>
  <%= link_to "edit", edit_post_path(p.id) %>
  <%= link_to "delete", post_path(p.id),:confirm => " Are you sure to delete this ?",method: :delete %>
  </li>
</ul>
</p> 
  <% end %>
  <%= link_to "Create Post", new_post_path %> 

app/views/posts/new.html.erb
<h1>Create a Post</h1>
<%= form_for @post do |p| %>
  <p>
  <%= p.label :author %>
  <%= p.text_field :author %>
  </p> 

  <p>
  <%= p.label :ptype, "Post Type"%>
  <%= p.text_field :ptype %>
  </p> 
  <p>
  <%= p.submit "Add a Post" %>
  </p> 

<% end %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>